/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    HelloWorld: (typeof import('./../src/components/HelloWorld.vue'))['default'];
    NaiveProvider: (typeof import('./../src/components/common/NaiveProvider.vue'))['default'];
    NavBar: (typeof import('./../src/components/common/NavBar.vue'))['default'];
    NCarousel: (typeof import('naive-ui'))['NCarousel'];
    NConfigProvider: (typeof import('naive-ui'))['NConfigProvider'];
    NDialogProvider: (typeof import('naive-ui'))['NDialogProvider'];
    NFlex: (typeof import('naive-ui'))['NFlex'];
    NLoadingBarProvider: (typeof import('naive-ui'))['NLoadingBarProvider'];
    NMenu: (typeof import('naive-ui'))['NMenu'];
    NMessageProvider: (typeof import('naive-ui'))['NMessageProvider'];
    NNotificationProvider: (typeof import('naive-ui'))['NNotificationProvider'];
    NSplit: (typeof import('naive-ui'))['NSplit'];
    RouterLink: (typeof import('vue-router'))['RouterLink'];
    RouterView: (typeof import('vue-router'))['RouterView'];
  }
}
