/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Contact: (typeof import('./../src/components/common/Contact.vue'))['default'];
    NaiveProvider: (typeof import('./../src/components/common/NaiveProvider.vue'))['default'];
    NavBar: (typeof import('./../src/components/common/NavBar.vue'))['default'];
    NavFooter: (typeof import('./../src/components/common/NavFooter.vue'))['default'];
    NBackTop: (typeof import('naive-ui'))['NBackTop'];
    NButton: (typeof import('naive-ui'))['NButton'];
    NCard: (typeof import('naive-ui'))['NCard'];
    NCarousel: (typeof import('naive-ui'))['NCarousel'];
    NConfigProvider: (typeof import('naive-ui'))['NConfigProvider'];
    NDialogProvider: (typeof import('naive-ui'))['NDialogProvider'];
    NFlex: (typeof import('naive-ui'))['NFlex'];
    NForm: (typeof import('naive-ui'))['NForm'];
    NGi: (typeof import('naive-ui'))['NGi'];
    NGrid: (typeof import('naive-ui'))['NGrid'];
    NGridItem: (typeof import('naive-ui'))['NGridItem'];
    NIcon: (typeof import('naive-ui'))['NIcon'];
    NInput: (typeof import('naive-ui'))['NInput'];
    NLoadingBarProvider: (typeof import('naive-ui'))['NLoadingBarProvider'];
    NMessageProvider: (typeof import('naive-ui'))['NMessageProvider'];
    NNotificationProvider: (typeof import('naive-ui'))['NNotificationProvider'];
    NPagination: (typeof import('naive-ui'))['NPagination'];
    NScrollbar: (typeof import('naive-ui'))['NScrollbar'];
    NTabPane: (typeof import('naive-ui'))['NTabPane'];
    NTabs: (typeof import('naive-ui'))['NTabs'];
    NTimeline: (typeof import('naive-ui'))['NTimeline'];
    NTimelineItem: (typeof import('naive-ui'))['NTimelineItem'];
    RouterLink: (typeof import('vue-router'))['RouterLink'];
    RouterView: (typeof import('vue-router'))['RouterView'];
  }
}
